name: newapp
description: Live voice room app with chat, gifts & leaderboard
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6

  # Socket (Realtime chat / live room)
  socket_io_client: ^2.0.3+1

  # Voice / Call (Zego)
  zego_uikit_prebuilt_call: ^3.18.2
  zego_express_engine: ^3.15.5

  # Utils
  uuid: ^4.4.0
  intl: ^0.19.0

  # State management (optional but useful)
  provider: ^6.1.2

  # HTTP (API call)
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true